### ISSUE TITLE
After I execute this command ‘python3 ./examples/miniedit.py’ in the VM，this error is displayed. What should I do?

### ISSUE THREAD

**Issue by saliay** [donadelden/miniV2G#6]
vagrant@linux:~/miniV2G$ python3 ./examples/miniedit.py
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(miniedit.py:3744): Gdk-CRITICAL **: 15:45:44.449: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Traceback (most recent call last):
  File "./examples/miniedit.py", line 6473, in <module>
    app = MiniEdit()
  File "./examples/miniedit.py", line 2246, in __init__
    Frame.__init__( self, parent )
  File "/usr/lib/python3.8/tkinter/__init__.py", line 3124, in __init__
    Widget.__init__(self, master, 'frame', cnf, {}, extra)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2566, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2533, in _setup
    master = _get_default_root()
  File "/usr/lib/python3.8/tkinter/__init__.py", line 298, in _get_default_root
    root = Tk()
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2270, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

How to resolve the above error？

**Comment by donadelden** [comment]
Hello,

miniedit is a tool with a graphic interface. Therefore, to use it, you may decide to open the Ubuntu graphic interface of the VM using Virtualbox/VMWare. 

Instead, if you prefer to access the VM using ssh (as I assume you are doing), you must activate the X11 forwarding by adding `-Y` to your ssh command, such as: `ssh -Y -p2222 vagrant@127.0.0.1`. I just tested this solution which is working fine.

**Comment by saliay** [comment]
> Hello,
> 
> miniedit is a tool with a graphic interface. Therefore, to use it, you may decide to open the Ubuntu graphic interface of the VM using Virtualbox/VMWare.
> 
> Instead, if you prefer to access the VM using ssh (as I assume you are doing), you must activate the X11 forwarding by adding `-Y` to your ssh command, such as: `ssh -Y -p2222 vagrant@127.0.0.1`. I just tested this solution which is working fine.

I try to use command 'ssh -Y -p2222 vagrant@127.0.0.1', but the same error is still displayed.
So I installed the project on the Ubuntu 20.
However, a new error appeared

$ sudo python3 miniedit.py
  File "/home/hwy/miniV2G/miniV2G/examples/miniedit.py", line 4797
    <<<<<<< HEAD
    ^
SyntaxError: invalid syntax

Is this error related to my Python version?

**Comment by donadelden** [comment]
It may be, but the installation is quite tricky, so I advise you to use the provided VM. 

Which OS is your host? 
If it is Ubuntu, it has to work. 
If instead, it is Windows, you may have to install an [X11 server](https://sourceforge.net/projects/xming/) and set display = 0 during installation. You may also need to add `export DISPLAY=:0;` to `.bashrc` of the VM. I don't have a Windows machine, so I cannot test it, and if you have any similar errors, I advise you to google them. 

However, the easiest and safest solution is to work inside the graphic environment of the provided VM directly.

**Comment by saliay** [comment]
In fact, I want to use the graphic environment of the provided VM and I failed.
I tried to download the VM from the vagrant cloud according to the link  [https://app.vagrantup.com/blackwiz4rd/boxes/ubuntu20.04-miniv2g]
<img width="923" alt="file" src="https://user-images.githubusercontent.com/35824455/184268433-63b628ab-8c93-4c94-a5a7-18de5fbde405.PNG">

But the file downloaded has no file name extension, just like '6ac903bb-02e4-4b35-b81f-d73586369257'.
I tried to manually add a file name extension, such as '.ova', '.ovf', '.vmx', '.vmtm' 
None of them is effective.

Is the link wrong? Did I download a wrong file? or Did I add the wrong file name extension?

**Comment by donadelden** [comment]
Please, learn how to use Vagrant (e.g., [here](https://medium.com/@JohnFoderaro/how-to-set-up-a-local-linux-environment-with-vagrant-163f0ba4da77)).

Briefly, if you run the two commands listed in the Readme file:
```
vagrant init blackwiz4rd/ubuntu20.04-miniv2g
vagrant up
```
You will end up having the VM in your Virtualbox.
